# Generated by Django 4.1.13 on 2024-01-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_instra_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_comment',
            field=models.BooleanField(default=False),
        ),
    ]
