# Generated by Django 4.1.13 on 2024-01-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_is_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_following',
            field=models.BooleanField(default=False),
        ),
    ]
